package com.clockify.gui;

import com.clockify.clockify.Database;
import com.clockify.model.Administrasi;
import com.clockify.model.Departemen;
import com.clockify.model.Karyawan;
import com.clockify.model.Manager;
import com.clockify.model.Teknisi;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author khusyasy
 */
public class FormKaryawan extends javax.swing.JDialog {
    private Karyawan k;
    private Database db;
    
    /**
     * Creates new form Karyawan
     */
    public FormKaryawan(java.awt.Frame parent, boolean modal, Database db, Karyawan k, ArrayList<Departemen> arrDep) {
        super(parent, modal);
        initComponents();
        this.db = db;
        this.k = k;
        DefaultComboBoxModel<Departemen> model = new DefaultComboBoxModel<>();
        model.addAll(arrDep);
        CBdepartemen.setModel(model);

        if (k != null) {
            TFnama.setText(k.getNama());
            if (k.getJenisKelamin().equals("M")) {
                buttonLaki.setSelected(true);
            } else if (k.getJenisKelamin().equals("F")) {
                buttonPerempuan.setSelected(true);
            }
            TFhp.setText(k.getNoHP());
            CBdepartemen.setSelectedItem(k.getDepartemen());
            if (k instanceof Administrasi) {
                CBposisi.setSelectedItem("administrasi");
            } else if (k instanceof Manager) {
                CBposisi.setSelectedItem("manager");
            } else if (k instanceof Teknisi) {
                CBposisi.setSelectedItem("teknisi");
            } else {
                CBposisi.setSelectedItem("pekerja");
            }
            TFemail.setText(k.getEmail());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGJK = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        TFnama = new javax.swing.JTextField();
        buttonLaki = new javax.swing.JRadioButton();
        buttonPerempuan = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFhp = new javax.swing.JTextField();
        TFemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CBdepartemen = new javax.swing.JComboBox<>();
        PFpassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CBposisi = new javax.swing.JComboBox<>();
        BTSave = new javax.swing.JButton();
        BTCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Nama");

        TFnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnamaActionPerformed(evt);
            }
        });

        BGJK.add(buttonLaki);
        buttonLaki.setText("Laki-laki");

        BGJK.add(buttonPerempuan);
        buttonPerempuan.setText("Perempuan");
        buttonPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerempuanActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("No Hp");

        jLabel5.setText("Email");

        jLabel6.setText("Departemen");

        jLabel7.setText("Password");

        jLabel8.setText("Posisi");

        CBposisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pekerja", "teknisi", "manager", "administrasi" }));

        BTSave.setText("Save");
        BTSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSaveActionPerformed(evt);
            }
        });

        BTCancel.setText("Cancel");
        BTCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(21, 21, 21)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TFhp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(buttonLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BTSave)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BTCancel))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(CBdepartemen, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(CBposisi, javax.swing.GroupLayout.Alignment.LEADING, 0, 106, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TFemail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PFpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(38, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(buttonLaki)
                    .addComponent(buttonPerempuan))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFhp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CBdepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CBposisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PFpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTSave)
                    .addComponent(BTCancel))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnamaActionPerformed

    private void buttonPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPerempuanActionPerformed

    private void BTSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSaveActionPerformed
        String nama = TFnama.getText();
        String jk = "";
        if(buttonLaki.isSelected()) {
            jk = "M";
        } else if(buttonPerempuan.isSelected()) {
            jk = "F";
        }
        String hp = TFhp.getText();
        Departemen departemen = (Departemen) CBdepartemen.getSelectedItem();
        String posisi = CBposisi.getSelectedItem().toString();
        String email = TFemail.getText();
        String password = PFpassword.getText();
        
        if (nama.isEmpty() || jk.isEmpty() || hp.isEmpty() || departemen == null || posisi.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            if (this.k == null) {
                db.executeUpdate("INSERT INTO karyawan (nama, jenisKelamin, noHP, id_departemen, posisi, email, password) VALUES (?, ?, ?, ?, ?, ?, ?)", nama, jk, hp, departemen.getId(), posisi, email, BCrypt.hashpw(password, BCrypt.gensalt()));
            } else {
                if (password.isEmpty()) {
                    db.executeUpdate("UPDATE karyawan SET nama = ?, jenisKelamin = ?, noHP = ?, id_departemen = ?, posisi = ?, email = ? WHERE id = ?", nama, jk, hp, departemen.getId(), posisi, email, this.k.getId());
                } else {
                    db.executeUpdate("UPDATE karyawan SET nama = ?, jenisKelamin = ?, noHP = ?, id_departemen = ?, posisi = ?, email = ?, password = ? WHERE id = ?", nama, jk, hp, departemen.getId(), posisi, email, BCrypt.hashpw(password, BCrypt.gensalt()), this.k.getId());
                }
            }

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            ((Menu) this.getOwner()).loadKaryawan();
            this.dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTSaveActionPerformed

    private void BTCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCancelActionPerformed
        ((Menu) this.getOwner()).loadKaryawan();
        this.dispose();
    }//GEN-LAST:event_BTCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGJK;
    private javax.swing.JButton BTCancel;
    private javax.swing.JButton BTSave;
    private javax.swing.JComboBox<Departemen> CBdepartemen;
    private javax.swing.JComboBox<String> CBposisi;
    private javax.swing.JPasswordField PFpassword;
    private javax.swing.JTextField TFemail;
    private javax.swing.JTextField TFhp;
    private javax.swing.JTextField TFnama;
    private javax.swing.JRadioButton buttonLaki;
    private javax.swing.JRadioButton buttonPerempuan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
