package com.clockify.gui;

import com.clockify.clockify.Database;
import com.clockify.model.Karyawan;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

import javax.swing.Timer;

/**
 *
 * @author khusyasy
 */
public class Menu extends javax.swing.JFrame {
    private Database db = new Database();
    private final Karyawan user;

    /**
     * Creates new form Menu
     * @param user
     */
    public Menu(Karyawan user) {
        this.user = user;
        initComponents();
        setupDisplay();
    }

    private void setupDisplay() {
        LBNama.setText(user.getNama());
        
        Timer timer = new Timer(1000, (ActionEvent e) -> {
            LBJam.setText(new SimpleDateFormat("HH:mm:ss").format(new Date()));
        });
        LBJam.setText(new SimpleDateFormat("HH:mm:ss").format(new Date()));
        timer.start();
        
        LBTanggal.setText(new SimpleDateFormat("EEEE, dd MMMM yyyy").format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        BTHadir = new javax.swing.JButton();
        BTIzin = new javax.swing.JButton();
        LBNama = new javax.swing.JLabel();
        LBTanggal = new javax.swing.JLabel();
        LBJam = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNama.setText("Nama");

        labelTanggal.setText("Tanggal");

        BTHadir.setText("Hadir");
        BTHadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTHadirActionPerformed(evt);
            }
        });

        BTIzin.setText("Izin");
        BTIzin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTIzinActionPerformed(evt);
            }
        });

        LBNama.setText("Nama");

        LBTanggal.setText("Tanggal");

        LBJam.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        LBJam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBJam.setText("JAM");
        LBJam.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LBJam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTIzin)
                        .addGap(18, 18, 18)
                        .addComponent(BTHadir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTanggal)
                            .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBTanggal)
                            .addComponent(LBNama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(LBJam, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelTanggal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LBNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LBTanggal)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTHadir)
                    .addComponent(BTIzin))
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("Absensi", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Karyawan", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Departemen", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTIzinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTIzinActionPerformed
        String alasan = JOptionPane.showInputDialog(this, "Alasan", "Izin", JOptionPane.QUESTION_MESSAGE);
        if (alasan == null || alasan.isEmpty() || alasan.isBlank()) {
            return;
        }
        try {
            db.executeUpdate("INSERT INTO absensi (waktu, id_karyawan, status, alasan) VALUES (?, ?, ?, ?)", new Date(), user.getId(), "izin", alasan);
            JOptionPane.showMessageDialog(this, "Izin berhasil dikirim", "Absensi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTIzinActionPerformed

    private void BTHadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTHadirActionPerformed
        try {
            db.executeUpdate("INSERT INTO absensi (waktu, id_karyawan, status) VALUES (?, ?, ?)", new Date(), user.getId(), "hadir");
            JOptionPane.showMessageDialog(this, "Absensi berhasil dikirim", "Absensi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTHadirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTHadir;
    private javax.swing.JButton BTIzin;
    private javax.swing.JLabel LBJam;
    private javax.swing.JLabel LBNama;
    private javax.swing.JLabel LBTanggal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTanggal;
    // End of variables declaration//GEN-END:variables
}
